### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by NucciTheBoss** [PSU-ICDS/torqueutils#1]
# The error:
```bash
$ python getjobinfo.py 25794736 --xml
Traceback (most recent call last):
  File "getjobinfo.py", line 262, in <module>
    main()
  File "/storage/home/jcn23/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/storage/home/jcn23/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/storage/home/jcn23/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/storage/home/jcn23/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "getjobinfo.py", line 218, in main
    retrieveJobInfo(str(jobid[0]), str(days), fout)
  File "getjobinfo.py", line 147, in retrieveJobInfo
    if findJobID(job_id, job_log_dir, log):
  File "getjobinfo.py", line 120, in findJobID
    grep_exec = subprocess.run(["grep", job_id], stdin=cat_exec.stdout, capture_output=True, text=True)
  File "/storage/home/jcn23/work/miniconda3/lib/python3.7/subprocess.py", line 490, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/storage/home/jcn23/work/miniconda3/lib/python3.7/subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/storage/home/jcn23/work/miniconda3/lib/python3.7/subprocess.py", line 1755, in _communicate
    self.stdout.errors)
  File "/storage/home/jcn23/work/miniconda3/lib/python3.7/subprocess.py", line 841, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 924160: invalid start byte
```

# Potential solution
It looks like the main issue here is the encoding/decoding format being used by Python to query the job info. In order to fix this, I may need to mess around with the encoding or change how I handle the system call. Will play around and see if there is a easy way for me to fix this issue.

* Trying using `ASCII`. That may help. The `suprocessCMD` function might be able to help too.

**Comment by NucciTheBoss** [comment]
Resolved the issue. The problem was how I was passing the job id using `nargs`
